"""External customer API - exposed outside the AIS network (DMZ / reverse proxy).

Auth: per-customer API key in header  X-API-Key: <key>
Keys are generated by Master Maintenance (POST /api/v1/customers/{plant}/{code}/api-key) and shown once.
Only the customer's own ledger is visible; only Mode A return slips can be created.

Endpoints
  GET  /api/ext/v1/holding                      -> pallets currently at this customer (by ID, with days)
  POST /api/ext/v1/return-slip                  -> create Mode A slip: pallets, vehicle, customer's challan
  GET  /api/ext/v1/return-slip/{slip_no}        -> status of a slip (IN_GATE / CLOSED / short list)
  POST /api/ext/v1/validate                     -> check a list of tags before loading (no state change)
  GET  /api/ext/v1/return-slip/{slip_no}/label?t=  -> printable A4 Pallet Return Slip with signed QR (no API key in URL)

QR on the label: AIS1|RS|<slip_no>|<plant>|<customer>|<vehicle>|<qty>|<yyMMddHHmm>|<check code>
The check code is signed by the server; the AIS IN gate rejects altered labels.
"""
import secrets
from datetime import datetime
from fastapi import APIRouter, Depends, HTTPException, Header, Request
from pydantic import BaseModel, Field
from sqlalchemy.orm import Session
from .. import models, services
from ..db import get_db
from ..security import hash_pw, check_pw, need, Principal, audit
from ..models import utcnow

router = APIRouter(prefix="/api/ext/v1", tags=["external-customer"])
admin = APIRouter(prefix="/api/v1", tags=["masters"])


def customer_auth(x_api_key: str = Header(default=None), db: Session = Depends(get_db)) -> models.Customer:
    if not x_api_key or len(x_api_key) < 12:
        raise HTTPException(401, "X-API-Key header required")
    prefix = x_api_key[:8]
    for c in db.query(models.Customer).filter(models.Customer.api_key_prefix == prefix, models.Customer.active == True).all():
        if c.api_key_hash and check_pw(x_api_key, c.api_key_hash):
            return c
    raise HTTPException(401, "Invalid API key")


@router.get("/holding")
def holding(c: models.Customer = Depends(customer_auth), db: Session = Depends(get_db)):
    now = utcnow()
    rows = db.query(models.Pallet).filter_by(customer_code=c.code, home_plant=c.plant_code, status="AT_CUSTOMER").order_by(models.Pallet.dispatch_date).all()
    limit = c.holding_limit_days
    return {"customer": c.code, "plant": c.plant_code, "count": len(rows), "holding_limit_days": limit,
            "pallets": [{"pallet_no": p.pallet_no, "tag": p.current_tag, "type": p.pallet_type, "challan": p.challan_ref,
                         "dispatched": p.dispatch_date, "days": (now - p.dispatch_date).days if p.dispatch_date else None,
                         "overdue": bool(limit and p.dispatch_date and (now - p.dispatch_date).days > limit)} for p in rows]}


class ValidateIn(BaseModel):
    tags: list[str] = Field(min_length=1, max_length=500)


@router.post("/validate")
def validate(body: ValidateIn, c: models.Customer = Depends(customer_auth), db: Session = Depends(get_db)):
    out = []
    for t in body.tags:
        tag, pal = services.resolve_tag(db, t)
        if not pal:
            out.append({"scanned": t, "ok": False, "reason": "unknown tag"})
        elif pal.customer_code != c.code or pal.status != "AT_CUSTOMER":
            out.append({"scanned": t, "ok": False, "pallet_no": pal.pallet_no, "reason": f"ledger shows {pal.status} {pal.customer_code or ''}".strip()})
        else:
            out.append({"scanned": t, "ok": True, "pallet_no": pal.pallet_no, "type": pal.pallet_type})
    return {"results": out, "ok_count": sum(1 for r in out if r["ok"])}


class ExtSlipIn(BaseModel):
    pallets: list[str] = Field(min_length=1, max_length=500, description="scanned tag numbers or pallet numbers")
    vehicle_no: str
    customer_challan_no: str
    customer_challan_date: datetime | None = None
    driver_name: str | None = None
    driver_mobile: str | None = None
    transporter: str | None = None
    client_ref: str | None = Field(default=None, description="idempotency key from customer system")
    remarks: str | None = None


@router.post("/return-slip")
def create_slip(body: ExtSlipIn, request: Request, c: models.Customer = Depends(customer_auth), db: Session = Depends(get_db)):
    if body.client_ref:
        dup = db.query(models.ReturnSlip).filter_by(customer_code=c.code, plant_code=c.plant_code, remarks=f"ref:{body.client_ref}").first()
        if dup:
            return _slip_out(db, dup) | {"duplicate": True}
    no = services.doc_number(db, c.plant_code, "RTS")
    sl = models.ReturnSlip(slip_no=no, plant_code=c.plant_code, customer_code=c.code, mode="A", vehicle_no=body.vehicle_no.upper().replace(" ", ""),
                           customer_challan_no=body.customer_challan_no, customer_challan_date=body.customer_challan_date,
                           driver_name=body.driver_name, driver_mobile=body.driver_mobile, source="EXT_API",
                           created_by=f"EXT:{c.code}", remarks=(f"ref:{body.client_ref}" if body.client_ref else None) or body.remarks)
    warnings = []; seen = set()
    for scv in body.pallets:
        tag, pal = services.resolve_tag(db, scv)
        if not pal:
            warnings.append(f"{scv}: unknown tag, listed as declared"); pno = scv
        else:
            pno = pal.pallet_no
            if pal.customer_code != c.code or pal.status != "AT_CUSTOMER":
                warnings.append(f"{pno}: ledger shows {pal.status} {pal.customer_code or ''}".strip())
            else:
                services.move(db, pal, "IN_RETURN", event_type="RETURN_SLIP_EXT", user_id=f"EXT:{c.code}", ref=no, customer=c.code)
        if pno in seen:
            continue
        seen.add(pno); db.add(models.ReturnSlipLine(slip_no=no, pallet_no=pno, declared=True))
    sl.declared_qty = len(seen); sl.status = "OPEN"
    db.add(sl)
    db.add(models.AuditLog(user_id=f"EXT:{c.code}", plant_code=c.plant_code, action="RETURN_SLIP_CREATE_EXT", entity="slip", entity_id=no,
                           new_value=body.model_dump_json(), ip=request.client.host if request.client else None))
    db.commit()
    return _slip_out(db, sl) | {"warnings": warnings}


def _slip_out(db, sl):
    lines = db.query(models.ReturnSlipLine).filter_by(slip_no=sl.slip_no).all()
    return {"slip_no": sl.slip_no, "status": sl.status, "plant": sl.plant_code, "customer": sl.customer_code, "vehicle_no": sl.vehicle_no,
            "customer_challan_no": sl.customer_challan_no, "declared_qty": sl.declared_qty, "created_at": sl.created_at, "closed_at": sl.closed_at,
            "qr_payload": services.slip_qr(sl),
            "label_url": f"/api/ext/v1/return-slip/{sl.slip_no}/label?t={services.label_token(sl.slip_no)}",
            "pallets": [{"pallet_no": l.pallet_no, "received": l.received, "exception": l.exception} for l in lines]}


@router.get("/return-slip/{slip_no}")
def get_slip(slip_no: str, c: models.Customer = Depends(customer_auth), db: Session = Depends(get_db)):
    sl = db.get(models.ReturnSlip, slip_no)
    if not sl or sl.customer_code != c.code or sl.plant_code != c.plant_code:
        raise HTTPException(404, "Slip not found")
    return _slip_out(db, sl)


@router.get("/return-slip/{slip_no}/label")
def slip_label(slip_no: str, t: str, db: Session = Depends(get_db)):
    """Customer prints this (browser -> Print) and sticks it on the vehicle / hands it to the driver."""
    from fastapi.responses import HTMLResponse
    import hmac
    if not hmac.compare_digest(t or "", services.label_token(slip_no)):
        raise HTTPException(403, "Invalid label link")
    sl = db.get(models.ReturnSlip, slip_no)
    if not sl:
        raise HTTPException(404, "Slip not found")
    return HTMLResponse(slip_label_html(db, sl))


def slip_label_html(db, sl) -> str:
    """Same A4 Pallet Return Slip as AIS prints (deck pattern), with the signed QR."""
    from .prints import slip_html
    return slip_html(db, sl, f"customer {sl.customer_code}")


# ---------------------------------------------------------------- key management (internal)
@admin.post("/customers/{plant}/{code}/api-key")
def issue_key(plant: str, code: str, request: Request, p: Principal = Depends(need("GLOBAL_MASTERS")), db: Session = Depends(get_db)):
    c = db.query(models.Customer).filter_by(code=code, plant_code=plant.upper()).first()
    if not c:
        raise HTTPException(404, "Customer not found")
    key = "ais_" + secrets.token_urlsafe(30)
    c.api_key_hash = hash_pw(key); c.api_key_prefix = key[:8]
    audit(db, p, "CUSTOMER_API_KEY", "customer", f"{code}@{plant}", request=request)
    db.commit()
    return {"customer": code, "plant": plant.upper(), "api_key": key, "note": "Shown once. Share with the customer over a secure channel."}


@admin.delete("/customers/{plant}/{code}/api-key")
def revoke_key(plant: str, code: str, request: Request, p: Principal = Depends(need("GLOBAL_MASTERS")), db: Session = Depends(get_db)):
    c = db.query(models.Customer).filter_by(code=code, plant_code=plant.upper()).first()
    if not c:
        raise HTTPException(404, "Customer not found")
    c.api_key_hash = None; c.api_key_prefix = None
    audit(db, p, "CUSTOMER_API_KEY_REVOKE", "customer", f"{code}@{plant}", request=request)
    db.commit()
    return {"ok": True}
